# Generated by Django 3.0.5 on 2020-04-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='content',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='slug',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='title',
            new_name='name',
        ),
    ]
