# Generated by Django 3.0.5 on 2020-04-16 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainUser', '0005_auto_20200416_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ok',
            new_name='profile',
        ),
    ]
