# Generated by Django 3.0.5 on 2020-04-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0006_auto_20200416_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.CharField(max_length=50)),
                ('car_vin', models.CharField(max_length=50)),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_state', models.IntegerField(default=0)),
                ('car_is_ok', models.BooleanField(default=True)),
            ],
        ),
    ]
