# Generated by Django 3.0.5 on 2020-04-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0007_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainUser.profile')),
            ],
        ),
    ]
