# Generated by Django 3.0.5 on 2020-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0008_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.ImageField(default='404.jpg', upload_to='source_imgs/cars/'),
        ),
    ]
