# Generated by Django 3.0.5 on 2020-04-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0009_cars_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.ImageField(default='404.jpg', upload_to='imgs/cars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='imgs/profile/'),
        ),
    ]
