# Generated by Django 3.0.5 on 2020-04-17 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0010_auto_20200417_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(default=[1, 2, 3], max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
