# Generated by Django 3.0.5 on 2020-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0011_profile_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRole',
        ),
    ]
